name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        resgistry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: nibatandukar/github-cicd
        tags: |
          type=sha
       ##     type=schedule
       ##     type=ref,event=branch
       ##     type=ref,event=pr
       ##     type=semver,pattern={{version}}
       ##     type=semver,pattern={{major}}.{{minor}}
       ##     type=semver,pattern={{major}}
        ##    type=sha
Insights

    Settings

github-action-demo/.github/workflows/
in
main

1

name: Python Package using Conda

2

​

3

on: [push]

4

​

5

jobs:

6

  build-linux:

7

    runs-on: ubuntu-latest

8

    strategy:

9

      max-parallel: 5

10

    steps:

11

    - uses: actions/checkout@v2

12

    - name: Login to DockerHub

13

      uses: docker/login-action@v1 

14

      with:

15

        resgistry: docker.io

16

        username: ${{ secrets.DOCKER_USERNAME }}

17

        password: ${{ secrets.DOCKER_PASSWORD }}

18

    - name: Extract metadata (tags, labels) for Docker

19

      id: meta

20

      uses: docker/metadata-action@v3

21

      with:

22

        images: nibatandukar/github-cicd

23

        tags: |

24

          type=sha

25

       ##     type=schedule

26

       ##     type=ref,event=branch

27

       ##     type=ref,event=pr

28

       ##     type=semver,pattern={{version}}

29

       ##     type=semver,pattern={{major}}.{{minor}}

30

       ##     type=semver,pattern={{major}}

31

        ##    type=sha

32

    - name: Build and Push Docker Images

33

      uses: docker/build-push-action@v2

34

      with:

Use Control + Space to trigger autocomplete in most situations.

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        image: nibatandukar/github-cicd
        resgistry: docker.io
        context: .
        push: true
###        tags: nibatandukar/github-cicd:latest
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Kubernets set context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Deploy to Cluster
      run: |
        ls
        cd k8s
        ls
        sed -i'' -e 's/IMAGE_LABEL/${{ steps.meta.outputs.tags }}/g' web.yaml
        kubectl apply -f web.yaml 
