name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        resgistry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: nibatandukar/github-cicd
        tags: |
          type=sha
       ##     type=schedule
       ##     type=ref,event=branch
       ##     type=ref,event=pr
       ##     type=semver,pattern={{version}}
       ##     type=semver,pattern={{major}}.{{minor}}
       ##     type=semver,pattern={{major}}
        ##    type=sha
    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        image: nibatandukar/github-cicd
        resgistry: docker.io
        context: .
        push: true
        tags: nibatandukar/github-cicd/${{ github.sha }}
###        tags: nibatandukar/github-cicd:latest
###        tags: ${{ steps.meta.outputs.tags }}
     ##   labels: ${{ steps.meta.outputs.labels }}
    - name: Kubernets set context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "IMAGE_LABEL"
        replace: "${{ github.sha }}"
        include: "k8s/web.yaml"
    - name: Deploy to Cluster
      run: |
        ls
        cd k8s
        kubectl apply -f web.yaml 
